name: Leah Buckareff
favicon: null
layout_spectrum: 0.9780069703701884
typography_spectrum: 0.50193
title: Leah Buckareff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2969544902443886
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.9950307090766728
purpose: []
